import os
import json
import re
import pandas as pd
from google import genai
from google.genai import types
from src.ai.fireworks.client import get_fireworks_client, MINMAX_ID, MODEL_ID



# =====================================================================
# ⚙️ CONFIGURATION & CLIENT INITIALIZATION
# =====================================================================


client = get_fireworks_client()

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))

# Navigate up to 'src/' and then down into 'Yt-data/'
YT_DATA_DIR = os.path.abspath(os.path.join(CURRENT_DIR, "..", "..", "Yt-data",))


def load_system_instruction(prompt_name: str) -> str:
    with open(f"{prompt_name}.txt", "r", encoding="utf-8") as f:
        return f.read().strip()

# =====================================================================
# 📂 STEP 1: LOAD METRIC BASELINES & GROUND TRUTH CONTEXT
# =====================================================================


def load_validation_payloads(trends_filename: str, context_filename: str = "video_context.json") -> tuple:
    """Loads validation tracking and source data using environment-agnostic absolute anchors."""

    # Dynamically build absolute paths to the Yt-data folder
    context_json_path = os.path.join(YT_DATA_DIR, context_filename)
    trends_json_path = os.path.join(YT_DATA_DIR, "trends", trends_filename)

    try:
        with open(context_json_path, "r", encoding="utf-8") as f:
            context_data = json.load(f)
    except FileNotFoundError:
        raise FileNotFoundError(f"❌ Core context mapping file missing at resolved absolute path: {context_json_path}")

    try:
        trends_df = pd.read_json(trends_json_path)
        top_cluster_id = trends_df.groupby('cluster_id')['views'].mean().idxmax()
        top_cluster = trends_df[trends_df['cluster_id'] == top_cluster_id]

        benchmarks = {
            "avg_views": float(top_cluster['views'].mean()),
            "target_like_ratio": float(top_cluster['like_ratio'].mean()),
            "sample_titles": top_cluster['clean_title'].head(3).tolist(),
            "sample_tags": list(set([tag for tags in top_cluster['extracted_hashtags'].head(3) for tag in tags]))
        }
    except Exception as e:
        print(f"⚠️ Performance metrics reference error ({e}). Using default telemetry bounds.")
        benchmarks = {
            "avg_views": 500000,
            "target_like_ratio": 0.05,
            "sample_titles": ["Trending Reference Title Option"],
            "sample_tags": ["#shorts", "#trending"]
        }

    return context_data, benchmarks

# =====================================================================
# 📂 STEP 2: LOAD GENERATOR CANDIDATES FILE
# =====================================================================

def load_generator_candidates(candidates_filename: str = "generated_content.json") -> list:
    """Reads the JSON file generated by your Generator script layer using directory anchoring."""

    # Looks for 'generated_content.json' in the exact same directory as discriminator.py
    candidates_json_path = os.path.join(CURRENT_DIR, candidates_filename)

    try:
        with open(candidates_json_path, "r", encoding="utf-8") as f:
            raw_data = json.load(f)

        titles_list = raw_data.get("titles", [])
        descriptions_list = raw_data.get("descriptions", [])
        hashtags_list = raw_data.get("hashtags", [])

        titles_dict = {item["id"]: item["text"] for item in titles_list if "id" in item and "text" in item}
        desc_dict = {item["id"]: item["text"] for item in descriptions_list if "id" in item and "text" in item}
        tags_dict = {item["id"]: item["tags"] for item in hashtags_list if "id" in item and "tags" in item}

        all_ids = set(titles_dict.keys()).union(desc_dict.keys()).union(tags_dict.keys())

        paired_candidates = []
        for v_id in sorted(all_ids):
            paired_candidates.append({
                "candidate_id": v_id,
                "title": titles_dict.get(v_id, ""),
                "description": desc_dict.get(v_id, ""),
                "hashtags": tags_dict.get(v_id, [])
            })

        print(f"📖 Successfully loaded {len(paired_candidates)} variations from absolute path.")
        return paired_candidates

    except FileNotFoundError:
        raise FileNotFoundError(f"❌ Expected generator output file missing at absolute path: {candidates_json_path}")
# =====================================================================
# ⚖️ STEP 3: MULTI-DIMENSIONAL AUDITING GENERATOR ENGINE
# =====================================================================
def run_discriminator_audit(candidates_list: list, context_data: dict, benchmarks: dict) -> str:
    """Acts as a strict YouTube algorithmic auditor checking metadata against historical trends and video truth."""

    video_truth_digest = {
        "topic": context_data.get("topic", ""),
        "core_message": context_data.get("core_message", ""),
        "multimodal_summary": context_data.get("multimodal_summary", ""),
        "key_entities": context_data.get("key_entities", []),
        "visible_text": context_data.get("visible_text", [])
    }

    evaluation_package = {
        "ground_truth_video_context": video_truth_digest,
        "historical_performance_benchmarks": benchmarks,
        "candidates_to_evaluate": candidates_list
    }

    system_instruction = load_system_instruction("d_prompt")

    # Inside src/models/discriminator/discriminator.py
    response = client.chat.completions.create(
        model=MINMAX_ID,  # accounts/fireworks/models/minimax-m3 or m2.7
        messages=[
            # 1. Put the instructions from d_prompt.txt here
            {
                "role": "system",
                "content": system_instruction
            },
            # 2. Put the actual data payload here for the model to analyze
            {
                "role": "user",
                "content": f"Analyze this payload and return the structured audit matrix:\n\n{json.dumps(evaluation_package, indent=2)}"
            }
        ],
        temperature=0.1,
        response_format={"type": "json_object"},
        # ✅ CORRECT EXTRA BODY FOR MINIMAX
        extra_body={
            "reasoning_effort": "low"  # Forces it to cut down thinking text and stick to the JSON schema
        }
    )
    # Extract raw execution numbers
    prompt_tokens = response.usage.prompt_tokens
    completion_tokens = response.usage.completion_tokens
    total_tokens = response.usage.total_tokens

    print(f"Input: {prompt_tokens} tokens | Output: {completion_tokens} tokens")

    # Llama 3.3 70B cost math ($0.90 per 1M tokens for input and output)
    total_cost = ((prompt_tokens / 1_000_000) * 0.90) + ((completion_tokens / 1_000_000) * 0.90)
    print(f"Approximate Call Cost: ${total_cost:.6f}")

    return response.choices[0].message.content

# =====================================================================
# 🚀 ROUTING RUNTIME INTERFACES
# =====================================================================
if __name__ == "__main__":
    # Point directly to your filenames inside Yt-data
    target_trends_file = "w_trends.json"
    generator_output_file = "generated_content.json"

    print("⚖️ Initializing Discriminator Verification Sequence...")

    # 1. Load context and trend tables safely using the correct keyword names
    video_context, performance_benchmarks = load_validation_payloads(
        trends_filename=target_trends_file,
        context_filename="video_context.json"
    )

    # 2. Extract elements seamlessly
    generator_candidates = load_generator_candidates(candidates_filename=generator_output_file)

    # 3. Execute the auditing core engine logic
    raw_audit_report = run_discriminator_audit(
        candidates_list=generator_candidates,
        context_data=video_context,
        benchmarks=performance_benchmarks
    )

    # 4. Save the audit report right inside the discriminator folder scope safely
    output_report_path = os.path.join(CURRENT_DIR, "audit_report.json")
    with open(output_report_path, "w", encoding="utf-8") as f:
        f.write(raw_audit_report)

    print(f"✅ Discriminator Audit Complete. Telemetry Report Generated -> {output_report_path}")
