import os
import json
import pandas as pd

# =====================================================================
# 🧭 DYNAMIC PATH ANCHORING (Git & Local Agnostic)
# =====================================================================
# This gets the absolute directory path of 'discriminator.py'
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))

# Navigate up to 'src/' and then down into 'Yt-data/'
YT_DATA_DIR = os.path.abspath(os.path.join(CURRENT_DIR, "..", "..", "Yt-data"))


def load_validation_payloads(trends_filename: str, context_filename: str = "video_context.json") -> tuple:
    """Loads validation tracking and source data using environment-agnostic absolute anchors."""

    # Dynamically build absolute paths to the Yt-data folder
    context_json_path = os.path.join(YT_DATA_DIR, context_filename)
    trends_json_path = os.path.join(YT_DATA_DIR, trends_filename)

    try:
        with open(context_json_path, "r", encoding="utf-8") as f:
            context_data = json.load(f)
    except FileNotFoundError:
        raise FileNotFoundError(f"❌ Core context mapping file missing at resolved absolute path: {context_json_path}")

    try:
        trends_df = pd.read_json(trends_json_path)
        top_cluster_id = trends_df.groupby('cluster_id')['views'].mean().idxmax()
        top_cluster = trends_df[trends_df['cluster_id'] == top_cluster_id]

        benchmarks = {
            "avg_views": float(top_cluster['views'].mean()),
            "target_like_ratio": float(top_cluster['like_ratio'].mean()),
            "sample_titles": top_cluster['clean_title'].head(3).tolist(),
            "sample_tags": list(set([tag for tags in top_cluster['extracted_hashtags'].head(3) for tag in tags]))
        }
    except Exception as e:
        print(f"⚠️ Performance metrics reference error ({e}). Using default telemetry bounds.")
        benchmarks = {
            "avg_views": 500000,
            "target_like_ratio": 0.05,
            "sample_titles": ["Trending Reference Title Option"],
            "sample_tags": ["#shorts", "#trending"]
        }

    return context_data, benchmarks


def load_generator_candidates(candidates_filename: str = "generated_content.json") -> list:
    """Reads the JSON file generated by your Generator script layer using directory anchoring."""

    # Looks for 'generated_content.json' in the exact same directory as discriminator.py
    candidates_json_path = os.path.join(CURRENT_DIR, candidates_filename)

    try:
        with open(candidates_json_path, "r", encoding="utf-8") as f:
            raw_data = json.load(f)

        titles_list = raw_data.get("titles", [])
        descriptions_list = raw_data.get("descriptions", [])
        hashtags_list = raw_data.get("hashtags", [])

        titles_dict = {item["id"]: item["text"] for item in titles_list if "id" in item and "text" in item}
        desc_dict = {item["id"]: item["text"] for item in descriptions_list if "id" in item and "text" in item}
        tags_dict = {item["id"]: item["tags"] for item in hashtags_list if "id" in item and "tags" in item}

        all_ids = set(titles_dict.keys()).union(desc_dict.keys()).union(tags_dict.keys())

        paired_candidates = []
        for v_id in sorted(all_ids):
            paired_candidates.append({
                "candidate_id": v_id,
                "title": titles_dict.get(v_id, ""),
                "description": desc_dict.get(v_id, ""),
                "hashtags": tags_dict.get(v_id, [])
            })

        print(f"📖 Successfully loaded {len(paired_candidates)} variations from absolute path.")
        return paired_candidates

    except FileNotFoundError:
        raise FileNotFoundError(f"❌ Expected generator output file missing at absolute path: {candidates_json_path}")